<?php
namespace NOSQL\Test;
use PHPUnit\Framework\TestCase;

/**
* Class NOSQLTest
* @package NOSQL\Test
* @author Fran López <fran.lopez84@hotmail.es>
* @version 1.0
* Autogenerated test [2019-01-03 15:23:58]
*/
class NOSQLTest extends TestCase {

    public function testConnection() {
        // TODO
    }

    public function testGenerate() {
        // TODO
    }

    public function testInsert() {
        // TODO
    }

    public function testUpdate() {
        // TODO
    }

    public function testDelete() {
        // TODO
    }

    public function testBulkInsert() {
        // TODO
    }

    public function testForms() {
        // TODO
    }
}
