<?php
namespace NOSQL\Controller;
use NOSQL\Controller\base\NOSQLBaseController;
use PSFS\base\config\Config;
use PSFS\base\Router;

/**
* Class NOSQLController
* @package NOSQL\Controller* @author Fran López <fran.lopez84@hotmail.es>
* @version 1.0
* @Api NOSQL
* Autogenerated controller [2019-01-03 15:23:58]
*/
class NOSQLController extends NOSQLBaseController {

    /**
    * Index
    * @GET
    * @label  Admin nosql composer
    * @action true
    * @visible true
    * @route /admin/nosql
    * @return string HTML
    */
    public function index() {
        return $this->render('index.html.twig');
    }

    /**
     * @GET
     * @route /admin/config/params
     * @visible false
     */
    public function configParams() {
        $response = array_merge(Config::$required, Config::$optional);
        $domains = Router::getInstance()->getDomains();
        $response[] = 'nosql.host';
        $response[] = 'nosql.port';
        $response[] = 'nosql.user';
        $response[] = 'nosql.password';
        $response[] = 'nosql.database';
        $response[] = 'nosql.replicaset';
        foreach ($domains as $domain => $routes) {
            $pDomain = str_replace('@', '', $domain);
            $pDomain = str_replace('/', '', $pDomain);
            $lowerDomain = strtolower($pDomain);
            $response[] = $lowerDomain . '.api.secret';
            $response[] = $lowerDomain . '.nosql.host';
            $response[] = $lowerDomain . '.nosql.port';
            $response[] = $lowerDomain . '.nosql.user';
            $response[] = $lowerDomain . '.nosql.password';
            $response[] = $lowerDomain . '.nosql.database';
            $response[] = $lowerDomain . '.nosql.replicaset';
        }
        return $this->json($response, 200);
    }

}
