filter:
  excluded_paths:
    - src/bin/*
    - src/command/*
    - src/tests/*
    - src/public/*
    - src/templates/*
    - locale/*
    - cache/*
    - config/*
    - logs/*
    - vendor/*

checks:
  php: true

tools:
  php_cs_fixer:
    config:
      level: psr12

build:
  environment:
    docker: true
    variables:
      PHP_VERSION: "8.3"
      DEBUG: ""
  nodes:
    analysis:
      dependencies:
        override:
          - docker-compose up -d php redis nosql
          - docker-compose exec -T php sh prepare-test-runtime.sh
          - docker-compose exec -T php composer install -o --no-interaction --no-progress --prefer-dist
      project_setup:
        override:
          - true
      tests:
        override:
          - php-scrutinizer-run
    services-tests:
      dependencies:
        override:
          - docker-compose up -d php redis nosql
          - docker-compose exec -T php sh prepare-test-runtime.sh
          - docker-compose exec -T php composer install -o --no-interaction --no-progress --prefer-dist
      project_setup:
        override:
          - true
      tests:
        stop_on_failure: true
        override:
          - docker-compose exec -T -e PSFS_REDIS_HOST=redis -e APP_ENVIRONMENT=test php sh scrutinizer-tests.sh
