<?php
/**
 * Autogenerated config file
 */
$serviceContainer = \Propel\Runtime\Propel::getServiceContainer();
$serviceContainer->checkVersion(2);
$serviceContainer->setAdapterClass('NOSQL', 'mysql');
$manager = new \Propel\Runtime\Connection\ConnectionManagerSingle('NOSQL');
$manager->setConfiguration([
    'dsn' => 'mysql:host=' . \PSFS\base\config\Config::getParam('db.host', null, 'nosql') . ';port=' . \PSFS\base\config\Config::getParam('db.port', null, 'nosql') . ';dbname=' . \PSFS\base\config\Config::getParam('db.name', null, 'nosql') . '',
    'user' => \PSFS\base\config\Config::getParam('db.user', null, 'nosql'),
    'password' => \PSFS\base\config\Config::getParam('db.password', null, 'nosql'),
    'classname' => \PSFS\base\types\helpers\PdoHelper::class,
    'model_paths' => array(
        0 => 'src',
        1 => 'vendor',
    ),
]);
$manager->setName('NOSQL');
$serviceContainer->setConnectionManager($manager);
$serviceContainer->setDefaultDatasource('NOSQL');
$serviceContainer->setLoggerConfiguration('defaultLogger', [
	'type' => 'rotating_file',
	'path' => LOG_DIR . '/db.log',
	'level' => 300,
	'max_files' => \PSFS\base\config\Config::getParam('db.log.max_files', 10, 'nosql'),
	'bubble' => true,
]);

require_once 'loadDatabase.php';
