<?php
/**
 * NOSQL Module
 * @author Fran López <fran.lopez84@hotmail.es>
 * @version 1.0
 * Autogenerated autoloader [2019-01-03 15:23:58]
 */
if(!defined("BASE_DIR"))
define("BASE_DIR", dirname( dirname(__DIR__) ) );

require_once __DIR__ . DIRECTORY_SEPARATOR . 'Config' . DIRECTORY_SEPARATOR . 'config.php';

if(!function_exists("NOSQL_Autoloader")) {
    // autoloader
    function NOSQL_Autoloader( $class ) {
        // it only autoload class into the Rain scope
        if (false !== preg_match('/^\\\?NOSQL/', $class)) {
            // Change order src
            $class = preg_replace('/^\\\?NOSQL/', 'NOSQL', $class);
            // transform the namespace in path
            $path = str_replace("\\", DIRECTORY_SEPARATOR, $class );
            // filepath
            $abs_path = __DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . $path . ".php";

            // require the file
            if(file_exists($abs_path)) {
                require_once $abs_path;
            }
        }
        return false;
    }

    // register the autoloader
    spl_autoload_register( "NOSQL_Autoloader" );
}
